In [4]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
data = pd.read_csv("customer_segmentation_100_records.csv",encoding="latin1")
df=pd.DataFrame(data)
print(df)

   Customer_ID  Age  Gender  Annual_Income  Spending_Score  Purchase_Frequency
0         C001   21  Female          21700              94                  14
1         C002   22    Male          23400              93                  13
2         C003   23  Female          25100              92                  12
3         C004   24    Male          26800              91                  11
4         C005   25  Female          28500              90                  10
..         ...  ...     ...            ...             ...                 ...
95        C096   46    Male         183200              49                   9
96        C097   47  Female         184900              48                   8
97        C098   48    Male         186600              47                   7
98        C099   49  Female         188300              46                   6
99        C100   50    Male         190000              95                   5

[100 rows x 6 columns]

In [5]:
df.head()

  Customer_ID  Age  Gender  Annual_Income  Spending_Score  Purchase_Frequency
0        C001   21  Female          21700              94                  14
1        C002   22    Male          23400              93                  13
2        C003   23  Female          25100              92                  12
3        C004   24    Male          26800              91                  11
4        C005   25  Female          28500              90                  10

In [6]:
df.tail()

   Customer_ID  Age  Gender  Annual_Income  Spending_Score  Purchase_Frequency
95        C096   46    Male         183200              49                   9
96        C097   47  Female         184900              48                   8
97        C098   48    Male         186600              47                   7
98        C099   49  Female         188300              46                   6
99        C100   50    Male         190000              95                   5

In [7]:
print(df.isnull().sum())

Customer_ID           0
Age                   0
Gender                0
Annual_Income         0
Spending_Score        0
Purchase_Frequency    0
dtype: int64

In [8]:

X=df[["Age"]]

model=KMeans(n_clusters=3, random_state=42)

df["Cluster"]=model.fit_predict(X)

print(df)

   Customer_ID  Age  Gender  Annual_Income  Spending_Score  \
0         C001   21  Female          21700              94
1         C002   22    Male          23400              93
2         C003   23  Female          25100              92
3         C004   24    Male          26800              91
4         C005   25  Female          28500              90
..         ...  ...     ...            ...             ...
95        C096   46    Male         183200              49
96        C097   47  Female         184900              48
97        C098   48    Male         186600              47
98        C099   49  Female         188300              46
99        C100   50    Male         190000              95

    Purchase_Frequency  Cluster
0                   14        0
1                   13        0
2                   12        0
3                   11        0
4                   10        0
..                 ...      ...
95                   9        1
96                   8        1
97                   7        1
98                   6        1
99                   5        1

[100 rows x 7 columns]